### ISSUE TITLE
Setting or Option for different "lib/" folder location

### ISSUE THREAD

**Issue by ThomasHineXYZ** [caiofsouza/AddLibrary#1]
Hello caiofsouza,

For the majority of my projects I mainly work with PHP, and I was wondering if it would be possible to have an option (maybe using the Sublime Projects settings) to have the lib/ folder moved somewhere else instead of on root?

My folder structure tends to have the server-side PHP in the root (organized in to different folders) with the web side of things being in a web/ folder on the root.

**Comment by caiofsouza** [comment]
Hi @guitaristtom,
Thanks for the suggestion!

This kind of configuration is on the roadmap of the plugin, but I can prioritize to release on next version.

**Comment by ThomasHineXYZ** [comment]
Thank you. That would be helpful.
